import type { WilayahSetting } from '../types';

export const DEFAULT_WILAYAH_DATA: WilayahSetting[] = [
  {
    wilayah: '1',
    sandiCabang: '601',
    branchCode: '601601',
    kodeCabang: 'WMD',
    namaOutlet: 'WILAYAH 01 - MEDAN',
    statusOutlet: 'KANWIL',
    alamat: 'JL. PEMUDA NO. 12, LANTAI IV MEDAN',
    kodePos: '20151',
    kelurahan: 'Aur',
    kecamatan: 'Medan Maimun',
    dati2: 'Kota Medan',
    provinsi: 'Sumatera Utara',
    telp: '061-4538166',
    kodeWilayah: '01',
    keterangan: 'WILAYAH 01 - MEDAN',
  },
  {
    wilayah: '2',
    sandiCabang: '602',
    branchCode: '602602',
    kodeCabang: 'WPD',
    namaOutlet: 'WILAYAH 02 - PADANG',
    statusOutlet: 'KANWIL',
    alamat: 'JL. DOBI NO. 1 LT. 3 PADANG.',
    kodePos: '25119',
    kelurahan: 'Kampung Pondok',
    kecamatan: 'Padang Barat',
    dati2: 'Kota Padang',
    provinsi: 'Sumatera Barat',
    telp: '(0751) 31952',
    kodeWilayah: '02',
    keterangan: 'WILAYAH 02 - PADANG',
  },
  {
    wilayah: '3',
    sandiCabang: '603',
    branchCode: '603603',
    kodeCabang: 'WPL',
    namaOutlet: 'WILAYAH 03 - PALEMBANG',
    statusOutlet: 'KANWIL',
    alamat: 'JL. JEND. SUDIRMAN NO. 132 - PALEMBANG',
    kodePos: '30126',
    kelurahan: '20 Ilir D. I',
    kecamatan: 'Ilir Timur I',
    dati2: 'Kota Palembang',
    provinsi: 'Sumatera Selatan',
    telp: '0711-353345, 0711-361965',
    kodeWilayah: '03',
    keterangan: 'WILAYAH 03 - PALEMBANG',
  },
  {
    wilayah: '4',
    sandiCabang: '604',
    branchCode: '604604',
    kodeCabang: 'WBN',
    namaOutlet: 'WILAYAH 04 - BANDUNG',
    statusOutlet: 'KANWIL',
    alamat: 'JL. PERINTIS KEMERDEKAAN NO. 3 - BANDUNG',
    kodePos: '40117',
    kelurahan: 'Babakan Ciamis',
    kecamatan: 'Sumur Bandung',
    dati2: 'Kota Bandung',
    provinsi: 'Jawa Barat',
    telp: '(022) 424215007',
    kodeWilayah: '04',
    keterangan: 'WILAYAH 04 - BANDUNG',
  },
  {
    wilayah: '5',
    sandiCabang: '605',
    branchCode: '605605',
    kodeCabang: 'WSM',
    namaOutlet: 'WILAYAH 05 - SEMARANG',
    statusOutlet: 'KANWIL',
    alamat: 'JL. MT. HARYONO NO.16, PURWODINATAN, KEC. SEMARANG TENGAH, KOTA SEMARANG, JAWA TENGAH',
    kodePos: '50137',
    kelurahan: 'Purwodinatan',
    kecamatan: 'Semarang Tengah',
    dati2: 'Kota Semarang',
    provinsi: 'Jawa Tengah',
    telp: '0',
    kodeWilayah: '05',
    keterangan: 'WILAYAH 05 - SEMARANG',
  },
  {
    wilayah: '6',
    sandiCabang: '606',
    branchCode: '606606',
    kodeCabang: 'WSY',
    namaOutlet: 'WILAYAH 06 - SURABAYA',
    statusOutlet: 'KANWIL',
    alamat: 'JL. JEND. A. YANI NO. 286 GEDUNG GRAHA PANGERAN LT.3-4',
    kodePos: '60234',
    kelurahan: 'Menanggal',
    kecamatan: 'Gayungan',
    dati2: 'Kota Surabaya',
    provinsi: 'Jawa Timur',
    telp: '(031) 8292820 - 26',
    kodeWilayah: '06',
    keterangan: 'WILAYAH 06 - SURABAYA',
  },
  {
    wilayah: '7',
    sandiCabang: '607',
    branchCode: '607607',
    kodeCabang: 'WMK',
    namaOutlet: 'WILAYAH 07 - MAKASSAR',
    statusOutlet: 'KANWIL',
    alamat: 'JL. JEND. SUDIRMAN NO. 1 - MAKASSAR',
    kodePos: '90115',
    kelurahan: 'Pisang Utara',
    kecamatan: 'Ujung Pandang',
    dati2: 'Kota Makassar',
    provinsi: 'Sulawesi Selatan',
    telp: '0411-3617488',
    kodeWilayah: '07',
    keterangan: 'WILAYAH 07 - MAKASSAR',
  },
  {
    wilayah: '8',
    sandiCabang: '608',
    branchCode: '608608',
    kodeCabang: 'WDR',
    namaOutlet: 'WILAYAH 08 - DENPASAR',
    statusOutlet: 'KANWIL',
    alamat: 'JL. RAYA PUPUTAN RENON NO. 27 - LT II, RENON, DENPASAR',
    kodePos: '80234',
    kelurahan: 'Kelod',
    kecamatan: 'Denpasar Timur',
    dati2: 'Kota Denpasar',
    provinsi: 'Bali',
    telp: '0361-233308',
    kodeWilayah: '08',
    keterangan: 'WILAYAH 08 - DENPASAR',
  },
  {
    wilayah: '9',
    sandiCabang: '609',
    branchCode: '609609',
    kodeCabang: 'WBJ',
    namaOutlet: 'WILAYAH 09 - BANJARMASIN',
    statusOutlet: 'KANWIL',
    alamat: 'JL. LAMBUNG MANGKURAT NO. 90 - BANJARMASIN',
    kodePos: '70111',
    kelurahan: 'Kertak Baru Ulu',
    kecamatan: 'Banjarmasin Tengah',
    dati2: 'Kota Banjarmasin',
    provinsi: 'Kalimantan Selatan',
    telp: '(0541) 3357063',
    kodeWilayah: '09',
    keterangan: 'WILAYAH 09 - BANJARMASIN',
  },
  {
    wilayah: '10',
    sandiCabang: '610',
    branchCode: '610610',
    kodeCabang: 'WJS',
    namaOutlet: 'WILAYAH 10 - JAKARTA SENAYAN',
    statusOutlet: 'KANWIL',
    alamat: 'JL. JEND. GATOT SUBROTO NO. 55, JAKARTA PUSAT',
    kodePos: '10210',
    kelurahan: 'Bendungan Hilir',
    kecamatan: 'Tanah Abang',
    dati2: 'Kota Administrasi Jakarta Pusat',
    provinsi: 'DKI Jakarta',
    telp: '021-5736054',
    kodeWilayah: '10',
    keterangan: 'WILAYAH 10 - JAKARTA SENAYAN',
  },
  {
    wilayah: '11',
    sandiCabang: '611',
    branchCode: '611611',
    kodeCabang: 'WMD',
    namaOutlet: 'WILAYAH 11 - MANADO',
    statusOutlet: 'KANWIL',
    alamat: 'JL. DOTULOLONG LASUT NO. 1 - MANADO',
    kodePos: '95122',
    kelurahan: 'Pinaesaan',
    kecamatan: 'Wenang',
    dati2: 'Kota Manado',
    provinsi: 'Sulawesi Utara',
    telp: '0431-855446',
    kodeWilayah: '11',
    keterangan: 'WILAYAH 11 - MANADO',
  },
  {
    wilayah: '12',
    sandiCabang: '612',
    branchCode: '612612',
    kodeCabang: 'WJK',
    namaOutlet: 'WILAYAH 12 - JAKARTA KOTA',
    statusOutlet: 'KANWIL',
    alamat: 'JL. LADA NO. 1 - JAKARTA',
    kodePos: '11110',
    kelurahan: 'Pinangsia',
    kecamatan: 'Taman Sari',
    dati2: 'Kota Administrasi Jakarta Barat',
    provinsi: 'DKI Jakarta',
    telp: '(021) 6901152',
    kodeWilayah: '12',
    keterangan: 'WILAYAH 12 - JAKARTA KOTA',
  },
  {
    wilayah: '14',
    sandiCabang: '614',
    branchCode: '614614',
    kodeCabang: 'WJB',
    namaOutlet: 'WILAYAH 14 - JAKARTA BSD',
    statusOutlet: 'KANWIL',
    alamat: 'GEDUNG BNI BSD LANTAI 7 JL. PAHLAWAN SERIBU KAV. SUNBURST LOT 1-5 LENGKONG GUDANG BSD CITY, KOTA TANGERANG SELATAN 15321',
    kodePos: '15321',
    kelurahan: 'Gudang',
    kecamatan: 'Serpong',
    dati2: 'Kota Tangerang Selatan',
    provinsi: 'Banten',
    telp: '021-80826800',
    kodeWilayah: '14',
    keterangan: 'WILAYAH 14 - JAKARTA BSD',
  },
  {
    wilayah: '15',
    sandiCabang: '615',
    branchCode: '615615',
    kodeCabang: 'WTY',
    namaOutlet: 'WILAYAH 15 - JAKARTA KEMAYORAN',
    statusOutlet: 'KANWIL',
    alamat: 'GEDUNG JATINEGARA BB OFFICE JL. JATINEGARA TIMUR NOMOR 88, KEL. BALIMESTER, KEC. JATINEGARA',
    kodePos: '13310',
    kelurahan: 'Bali Mester',
    kecamatan: 'Jatinegara',
    dati2: 'Jakarta Timur',
    provinsi: 'DKI Jakarta',
    telp: '021-22898972',
    kodeWilayah: '15',
    keterangan: 'WILAYAH 15 - JAKARTA KEMAYORAN',
  },
  {
    wilayah: '16',
    sandiCabang: '616',
    branchCode: '616616',
    kodeCabang: 'WPU',
    namaOutlet: 'WILAYAH 16 - PAPUA',
    statusOutlet: 'KANWIL',
    alamat: 'JL. KELAPA 2 ENTROP, KOTA JAYAPURA',
    kodePos: '99224',
    kelurahan: 'Entrop',
    kecamatan: 'Jayapura Selatan',
    dati2: 'Kota Jayapura',
    provinsi: 'Papua',
    telp: '(0967) 522354',
    kodeWilayah: '16',
    keterangan: 'WILAYAH 16 - PAPUA',
  },
  {
    wilayah: '17',
    sandiCabang: '617',
    branchCode: '617617',
    kodeCabang: 'WYK',
    namaOutlet: 'WILAYAH 17 - YOGYAKARTA',
    statusOutlet: 'KANWIL',
    alamat: 'JL. TRIKORA NO.1 YOGYAKARTA',
    kodePos: '55122',
    kelurahan: 'Ngupasan',
    kecamatan: 'Gondomanan',
    dati2: 'Kota Yogyakarta',
    provinsi: 'D.I. Yogyakarta',
    telp: 'tersedia',
    kodeWilayah: '17',
    keterangan: 'WILAYAH 17 - YOGYAKARTA',
  },
  {
    wilayah: '18',
    sandiCabang: '618',
    branchCode: '618618',
    kodeCabang: 'WMA',
    namaOutlet: 'WILAYAH 18 - MALANG',
    statusOutlet: 'KANWIL',
    alamat: 'JL. JENDERAL BASUKI RAHMAT NO.75-77, KAUMAN, KEC. KLOJEN, KOTA MALANG, JAWA TIMUR 65119',
    kodePos: '65119',
    kelurahan: 'Kauman',
    kecamatan: 'Klojen',
    dati2: 'Kota Malang',
    provinsi: 'Jawa Timur',
    telp: '(0341) 361945',
    kodeWilayah: '18',
    keterangan: 'WILAYAH 18 - MALANG',
  },
];

/**
 * Standardize any partial or legacy WilayahSetting item into a complete, clean WilayahSetting
 */
export function normalizeWilayahItem(item: Partial<WilayahSetting>, index = 0): WilayahSetting {
  const wilayahStr = String(item.wilayah || item.kodeWilayah || (index + 1)).trim();
  const digit2 = wilayahStr.replace(/\D/g, '').padStart(2, '0') || '01';
  const sandi = item.sandiCabang ? String(item.sandiCabang).trim() : `6${digit2}`;
  const branch = item.branchCode ? String(item.branchCode).trim() : `${sandi}${sandi}`;
  const nama = item.namaOutlet || item.keterangan || `WILAYAH ${digit2}`;

  return {
    wilayah: wilayahStr,
    sandiCabang: sandi,
    branchCode: branch,
    kodeCabang: item.kodeCabang ? String(item.kodeCabang).trim().toUpperCase() : '',
    namaOutlet: nama,
    statusOutlet: item.statusOutlet ? String(item.statusOutlet).trim().toUpperCase() : 'KANWIL',
    alamat: item.alamat ? String(item.alamat).trim() : '',
    kodePos: item.kodePos ? String(item.kodePos).trim() : '',
    kelurahan: item.kelurahan ? String(item.kelurahan).trim() : '',
    kecamatan: item.kecamatan ? String(item.kecamatan).trim() : '',
    dati2: item.dati2 ? String(item.dati2).trim() : '',
    provinsi: item.provinsi ? String(item.provinsi).trim() : '',
    telp: item.telp ? String(item.telp).trim() : '',
    kodeWilayah: item.kodeWilayah || digit2,
    keterangan: item.keterangan || nama,
  };
}
