import type { MasterRow, TargetRow } from '../types';

export const SAMPLE_MASTER_ROWS: MasterRow[] = [
  {
    Wilayah: 'Wilayah 1 - DKI Jakarta',
    Sandi: '008001',
    Cabang: 'KC Jakarta Sudirman',
    'Branch Code': 'JKT-SDR-01',
    'Kode Cabang': '0101',
    'Nama Outlet': 'KC Sudirman Sentral Senayan',
    'Status Outlet': 'Aktif',
    ALAMAT: 'Jl. Jend. Sudirman Kav. 52-53, Senayan',
    'KODE POS': '12190',
    Kelurahan: 'Senayan',
    Kecamatan: 'Kebayoran Baru',
    'Dati II': 'Kota Jakarta Selatan',
    'Kode Dati II': '3174',
    Provinsi: 'DKI Jakarta',
    Telp: '021-52901234',
  },
  {
    Wilayah: 'Wilayah 1 - DKI Jakarta',
    Sandi: '008002',
    Cabang: 'KCP Jakarta SCBD',
    'Branch Code': 'JKT-SCBD-02',
    'Kode Cabang': '0102',
    'Nama Outlet': 'KCP Electronic City SCBD',
    'Status Outlet': 'Aktif',
    ALAMAT: 'Kawasan Niaga Terpadu Sudirman Lot 8',
    'KODE POS': '12190',
    Kelurahan: 'Senayan',
    Kecamatan: 'Kebayoran Baru',
    'Dati II': 'Kota Jakarta Selatan',
    'Kode Dati II': '3174',
    Provinsi: 'DKI Jakarta',
    Telp: '021-5154321',
  },
  {
    Wilayah: 'Wilayah 1 - DKI Jakarta',
    Sandi: '008003',
    Cabang: 'KC Jakarta Thamrin',
    'Branch Code': 'JKT-THM-01',
    'Kode Cabang': '0103',
    'Nama Outlet': 'KC Plaza Indonesia Thamrin',
    'Status Outlet': 'Aktif',
    ALAMAT: 'Jl. M.H. Thamrin Kav. 28-30',
    'KODE POS': '10350',
    Kelurahan: 'Gondangdia',
    Kecamatan: 'Menteng',
    'Dati II': 'Kota Jakarta Pusat',
    'Kode Dati II': '3171',
    Provinsi: 'DKI Jakarta',
    Telp: '021-3983888',
  },
  {
    Wilayah: 'Wilayah 1 - DKI Jakarta',
    Sandi: '008004',
    Cabang: 'KCP Kelapa Gading Boulevard',
    'Branch Code': 'JKT-KLG-01',
    'Kode Cabang': '0104',
    'Nama Outlet': 'KCP Mall Kelapa Gading 3',
    'Status Outlet': 'Aktif',
    ALAMAT: 'Jl. Boulevard Raya Blok M, Kelapa Gading',
    'KODE POS': '14240',
    Kelurahan: 'Kelapa Gading Timur',
    Kecamatan: 'Kelapa Gading',
    'Dati II': 'Kota Jakarta Utara',
    'Kode Dati II': '3172',
    Provinsi: 'DKI Jakarta',
    Telp: '021-45853000',
  },
  {
    Wilayah: 'Wilayah 2 - Jawa Barat',
    Sandi: '008010',
    Cabang: 'KC Bandung Asia Afrika',
    'Branch Code': 'BDG-AA-01',
    'Kode Cabang': '0201',
    'Nama Outlet': 'KC Heritage Asia Afrika Bandung',
    'Status Outlet': 'Aktif',
    ALAMAT: 'Jl. Asia Afrika No. 107',
    'KODE POS': '40111',
    Kelurahan: 'Braga',
    Kecamatan: 'Sumur Bandung',
    'Dati II': 'Kota Bandung',
    'Kode Dati II': '3273',
    Provinsi: 'Jawa Barat',
    Telp: '022-4231234',
  },
  {
    Wilayah: 'Wilayah 2 - Jawa Barat',
    Sandi: '008011',
    Cabang: 'KCP Bandung Dago',
    'Branch Code': 'BDG-DG-02',
    'Kode Cabang': '0202',
    'Nama Outlet': 'KCP Ir. H. Djuanda',
    'Status Outlet': 'Aktif',
    ALAMAT: 'Jl. Ir. H. Djuanda No. 84',
    'KODE POS': '40132',
    Kelurahan: 'Lebak Siliwangi',
    Kecamatan: 'Coblong',
    'Dati II': 'Kota Bandung',
    'Kode Dati II': '3273',
    Provinsi: 'Jawa Barat',
    Telp: '022-2505500',
  },
  {
    Wilayah: 'Wilayah 2 - Jawa Barat',
    Sandi: '008012',
    Cabang: 'KC Bogor Pajajaran',
    'Branch Code': 'BGR-PJJ-01',
    'Kode Cabang': '0203',
    'Nama Outlet': 'KC Pajajaran Raya Bogor',
    'Status Outlet': 'Aktif',
    ALAMAT: 'Jl. Pajajaran No. 23',
    'KODE POS': '16143',
    Kelurahan: 'Bantarjati',
    Kecamatan: 'Bogor Utara',
    'Dati II': 'Kota Bogor',
    'Kode Dati II': '3271',
    Provinsi: 'Jawa Barat',
    Telp: '0251-8311222',
  },
  {
    Wilayah: 'Wilayah 3 - Jawa Tengah & DIY',
    Sandi: '008020',
    Cabang: 'KC Semarang Pemuda',
    'Branch Code': 'SMG-PMD-01',
    'Kode Cabang': '0301',
    'Nama Outlet': 'KC Pemuda Central Semarang',
    'Status Outlet': 'Aktif',
    ALAMAT: 'Jl. Pemuda No. 150',
    'KODE POS': '50132',
    Kelurahan: 'Sekayu',
    Kecamatan: 'Semarang Tengah',
    'Dati II': 'Kota Semarang',
    'Kode Dati II': '3374',
    Provinsi: 'Jawa Tengah',
    Telp: '024-3551122',
  },
  {
    Wilayah: 'Wilayah 3 - Jawa Tengah & DIY',
    Sandi: '008021',
    Cabang: 'KC Yogyakarta Sudirman',
    'Branch Code': 'YOG-SDR-01',
    'Kode Cabang': '0302',
    'Nama Outlet': 'KC Tugu Malioboro Sudirman',
    'Status Outlet': 'Aktif',
    ALAMAT: 'Jl. Jend. Sudirman No. 32',
    'KODE POS': '55233',
    Kelurahan: 'Gowongan',
    Kecamatan: 'Jetis',
    'Dati II': 'Kota Yogyakarta',
    'Kode Dati II': '3471',
    Provinsi: 'D.I. Yogyakarta',
    Telp: '0274-561234',
  },
  {
    Wilayah: 'Wilayah 4 - Jawa Timur',
    Sandi: '008030',
    Cabang: 'KC Surabaya Basuki Rahmat',
    'Branch Code': 'SBY-BSR-01',
    'Kode Cabang': '0401',
    'Nama Outlet': 'KC Basuki Rahmat Sentral',
    'Status Outlet': 'Aktif',
    ALAMAT: 'Jl. Basuki Rahmat No. 122-138',
    'KODE POS': '60271',
    Kelurahan: 'Embong Kaliasin',
    Kecamatan: 'Genteng',
    'Dati II': 'Kota Surabaya',
    'Kode Dati II': '3578',
    Provinsi: 'Jawa Timur',
    Telp: '031-5341234',
  },
  {
    Wilayah: 'Wilayah 4 - Jawa Timur',
    Sandi: '008031',
    Cabang: 'KCP Surabaya Darmo',
    'Branch Code': 'SBY-DRM-02',
    'Kode Cabang': '0402',
    'Nama Outlet': 'KCP Raya Darmo Surabaya',
    'Status Outlet': 'Aktif',
    ALAMAT: 'Jl. Raya Darmo No. 55',
    'KODE POS': '60265',
    Kelurahan: 'Keputran',
    Kecamatan: 'Tegalsari',
    'Dati II': 'Kota Surabaya',
    'Kode Dati II': '3578',
    Provinsi: 'Jawa Timur',
    Telp: '031-5678901',
  },
  {
    Wilayah: 'Wilayah 5 - Bali & Nusa Tenggara',
    Sandi: '008040',
    Cabang: 'KC Denpasar Gajah Mada',
    'Branch Code': 'DPS-GJM-01',
    'Kode Cabang': '0501',
    'Nama Outlet': 'KC Gajah Mada Denpasar',
    'Status Outlet': 'Aktif',
    ALAMAT: 'Jl. Gajah Mada No. 1',
    'KODE POS': '80112',
    Kelurahan: 'Dauh Puri',
    Kecamatan: 'Denpasar Barat',
    'Dati II': 'Kota Denpasar',
    'Kode Dati II': '5171',
    Provinsi: 'Bali',
    Telp: '0361-224500',
  },
  {
    Wilayah: 'Wilayah 6 - Sumatera Utara',
    Sandi: '008050',
    Cabang: 'KC Medan Imam Bonjol',
    'Branch Code': 'MDN-IB-01',
    'Kode Cabang': '0601',
    'Nama Outlet': 'KC Imam Bonjol Medan',
    'Status Outlet': 'Aktif',
    ALAMAT: 'Jl. Imam Bonjol No. 16-D',
    'KODE POS': '20112',
    Kelurahan: 'Petisah Tengah',
    Kecamatan: 'Medan Petisah',
    'Dati II': 'Kota Medan',
    'Kode Dati II': '1271',
    Provinsi: 'Sumatera Utara',
    Telp: '061-4518000',
  },
];

export const SAMPLE_TARGET_ROWS: TargetRow[] = [
  {
    No: 1,
    Wilayah: 'Wilayah 1 - DKI Jakarta',
    Sandi: '',
    Cabang: '',
    'Branch Code': '',
    'Kode Cabang': '',
    'Nama Outlet': '',
    'Status Outlet': '',
    ALAMAT: 'Kawasan Mega Kuningan Lot 5.1 (Alamat Sementara)',
    'KODE POS': '10350',
    Kelurahan: 'Gondangdia',
    Kecamatan: 'Menteng',
    'Dati II': 'Kota Jakarta Pusat',
    'Kode Dati II': '3171',
    Provinsi: 'DKI Jakarta',
    'SUMBER DATA': 'BATCH_MERCHANT_2026_09A',
  },
  {
    No: 2,
    Wilayah: 'Wilayah 1 - DKI Jakarta',
    Sandi: '',
    Cabang: '',
    'Branch Code': '',
    'Kode Cabang': '',
    'Nama Outlet': '',
    'Status Outlet': '',
    ALAMAT: 'Kawasan Niaga Terpadu Sudirman Lot 8 (EDC Point)',
    'KODE POS': '12190',
    Kelurahan: 'Senayan',
    Kecamatan: 'Kebayoran Baru',
    'Dati II': 'Kota Jakarta Selatan',
    'Kode Dati II': '3174',
    Provinsi: 'DKI Jakarta',
    'SUMBER DATA': 'BATCH_MERCHANT_2026_09A',
  },
  {
    No: 3,
    Wilayah: 'Wilayah 1 - DKI Jakarta',
    Sandi: '',
    Cabang: '',
    'Branch Code': '',
    'Kode Cabang': '',
    'Nama Outlet': '',
    'Status Outlet': '',
    ALAMAT: 'Boulevard Raya Kelapa Gading Blok M No. 8',
    'KODE POS': '14240',
    Kelurahan: 'Kelapa Gading Timur',
    Kecamatan: 'Kelapa Gading',
    'Dati II': 'Kota Jakarta Utara',
    'Kode Dati II': '3172',
    Provinsi: 'DKI Jakarta',
    'KODE POS PTEN': '14250', // PTEN Discrepancy!
    'SUMBER DATA': 'BATCH_MERCHANT_2026_09A',
  },
  {
    No: 4,
    Wilayah: 'Wilayah 2 - Jawa Barat',
    Sandi: '',
    Cabang: '',
    'Branch Code': '',
    'Kode Cabang': '',
    'Nama Outlet': '',
    'Status Outlet': '',
    ALAMAT: 'Jl. Asia Afrika Komplek Heritage Blok C',
    'KODE POS': '40111',
    Kelurahan: 'Braga',
    Kecamatan: 'Sumur Bandung',
    'Dati II': 'Kota Bandung',
    'Kode Dati II': '3273',
    Provinsi: 'Jawa Barat',
    'SUMBER DATA': 'BATCH_REGIONAL_JABAR_01',
  },
  {
    No: 5,
    Wilayah: 'Wilayah 2 - Jawa Barat',
    Sandi: '',
    Cabang: '',
    'Branch Code': '',
    'Kode Cabang': '',
    'Nama Outlet': '',
    'Status Outlet': '',
    ALAMAT: 'Jl. Djuanda Simpang Dago Atas',
    'KODE POS': '40132',
    Kelurahan: 'Lebak Siliwangi',
    Kecamatan: 'Coblong',
    'Dati II': 'Kota Bandung',
    'Kode Dati II': '3273',
    Provinsi: 'Jawa Barat',
    'SUMBER DATA': 'BATCH_REGIONAL_JABAR_01',
  },
  {
    No: 6,
    Wilayah: 'Wilayah 2 - Jawa Barat',
    Sandi: '',
    Cabang: '',
    'Branch Code': '',
    'Kode Cabang': '',
    'Nama Outlet': '',
    'Status Outlet': '',
    ALAMAT: 'Jl. Pajajaran No. 25 Depan Rumah Sakit',
    'KODE POS': '16143',
    Kelurahan: 'Bantarjati',
    Kecamatan: 'Bogor Utara',
    'Dati II': 'Kota Bogor',
    'Kode Dati II': '3271',
    Provinsi: 'Jawa Barat',
    'SUMBER DATA': 'BATCH_REGIONAL_JABAR_01',
  },
  {
    No: 7,
    Wilayah: 'Wilayah 3 - Jawa Tengah & DIY',
    Sandi: '',
    Cabang: '',
    'Branch Code': '',
    'Kode Cabang': '',
    'Nama Outlet': '',
    'Status Outlet': '',
    ALAMAT: 'Kawasan Bisnis Pemuda Plaza Simpang Lima',
    'KODE POS': '50132',
    Kelurahan: 'Sekayu',
    Kecamatan: 'Semarang Tengah',
    'Dati II': 'Kota Semarang',
    'Kode Dati II': '3374',
    Provinsi: 'Jawa Tengah',
    'SUMBER DATA': 'BATCH_JATENG_EDC_04',
  },
  {
    No: 8,
    Wilayah: 'Wilayah 3 - Jawa Tengah & DIY',
    Sandi: '',
    Cabang: '',
    'Branch Code': '',
    'Kode Cabang': '',
    'Nama Outlet': '',
    'Status Outlet': '',
    ALAMAT: 'Dekat Tugu Stasiun Tugu Yogyakarta',
    'KODE POS': '55233',
    Kelurahan: 'Gowongan',
    Kecamatan: 'Jetis',
    'Dati II': 'Kota Yogyakarta',
    'Kode Dati II': '3471',
    Provinsi: 'D.I. Yogyakarta',
    'SUMBER DATA': 'BATCH_JATENG_EDC_04',
  },
  {
    No: 9,
    Wilayah: 'Wilayah 4 - Jawa Timur',
    Sandi: '',
    Cabang: '',
    'Branch Code': '',
    'Kode Cabang': '',
    'Nama Outlet': '',
    'Status Outlet': '',
    ALAMAT: 'Basuki Rahmat Sentral Bisnis Kav. 12',
    'KODE POS': '60271',
    Kelurahan: 'Embong Kaliasin',
    Kecamatan: 'Genteng',
    'Dati II': 'Kota Surabaya',
    'Kode Dati II': '3578',
    Provinsi: 'Jawa Timur',
    'SUMBER DATA': 'BATCH_JATIM_OPS_08',
  },
  {
    No: 10,
    Wilayah: 'Wilayah 4 - Jawa Timur',
    Sandi: '',
    Cabang: '',
    'Branch Code': '',
    'Kode Cabang': '',
    'Nama Outlet': '',
    'Status Outlet': '',
    ALAMAT: 'Raya Darmo No. 60 Depan Taman Bungkul',
    'KODE POS': '60265',
    Kelurahan: 'Keputran',
    Kecamatan: 'Tegalsari',
    'Dati II': 'Kota Surabaya',
    'Kode Dati II': '3578',
    Provinsi: 'Jawa Timur',
    'KODE POS PTEN': '60260', // PTEN Discrepancy!
    'SUMBER DATA': 'BATCH_JATIM_OPS_08',
  },
  {
    No: 11,
    Wilayah: 'Wilayah 5 - Bali & Nusa Tenggara',
    Sandi: '',
    Cabang: '',
    'Branch Code': '',
    'Kode Cabang': '',
    'Nama Outlet': '',
    'Status Outlet': '',
    ALAMAT: 'Jl. Gajah Mada Pusat Pertokoan Denpasar',
    'KODE POS': '80112',
    Kelurahan: 'Dauh Puri',
    Kecamatan: 'Denpasar Barat',
    'Dati II': 'Kota Denpasar',
    'Kode Dati II': '5171',
    Provinsi: 'Bali',
    'SUMBER DATA': 'BATCH_BALI_02',
  },
  {
    No: 12,
    Wilayah: 'Wilayah 6 - Sumatera Utara',
    Sandi: '',
    Cabang: '',
    'Branch Code': '',
    'Kode Cabang': '',
    'Nama Outlet': '',
    'Status Outlet': '',
    ALAMAT: 'Jl. Imam Bonjol Pertokoan Petisah',
    'KODE POS': '20112',
    Kelurahan: 'Petisah Tengah',
    Kecamatan: 'Medan Petisah',
    'Dati II': 'Kota Medan',
    'Kode Dati II': '1271',
    Provinsi: 'Sumatera Utara',
    'SUMBER DATA': 'BATCH_SUMUT_01',
  },
  {
    No: 13,
    Wilayah: 'Wilayah 7 - Kalimantan Barat',
    Sandi: '',
    Cabang: '',
    'Branch Code': '',
    'Kode Cabang': '',
    'Nama Outlet': '',
    'Status Outlet': '',
    ALAMAT: 'Jl. Gajah Mada Pasar Flamboyan (Outlet Baru)',
    'KODE POS': '78121', // Unmatched in Master!
    Kelurahan: 'Benua Melayu Darat',
    Kecamatan: 'Pontianak Selatan',
    'Dati II': 'Kota Pontianak',
    'Kode Dati II': '6171',
    Provinsi: 'Kalimantan Barat',
    'SUMBER DATA': 'BATCH_NEW_OUTLETS_KALIMANTAN',
  },
  {
    No: 14,
    Wilayah: 'Wilayah 8 - Sulawesi Selatan',
    Sandi: '',
    Cabang: '',
    'Branch Code': '',
    'Kode Cabang': '',
    'Nama Outlet': '',
    'Status Outlet': '',
    ALAMAT: 'Jl. Ahmad Yani No. 15 (Outlet Baru)',
    'KODE POS': '90111', // Unmatched in Master!
    Kelurahan: 'Pattunuang',
    Kecamatan: 'Wajo',
    'Dati II': 'Kota Makassar',
    'Kode Dati II': '7371',
    Provinsi: 'Sulawesi Selatan',
    'KODE POS PTEN': '90115', // PTEN Discrepancy + Unmatched!
    'SUMBER DATA': 'BATCH_NEW_OUTLETS_SULAWESI',
  },
];
